### ISSUE TITLE
Can’t access multiple keyframes in -w mode

### ISSUE THREAD

**Issue by arrowtype** [goodhertz/coldtype-examples#1]
In the [animating](https://github.com/goodhertz/coldtype-examples/tree/6b757d96afeab798bf9291b7abd58d0b12864552#animating) instructions, you say:

> While it’s hanging, you can type in little mnemonics to trigger different actions in the coldtype renderer.
> 
> For instance, with the above process still running, try typing—
> ```
> pf 30
> ```

This works fine, rendering the letters in the viewer a little differently than before. 

However, this part errors for me:

> You can type any number of frame indices here, to preview multiple frames at once, like so:
> ```
> pf 35, 36, 37
> ```

Here’s what I get:

```
▶ coldtype animations/808.py -w
... watching ...
>>> CAUGHT COLDTYPE RENDER
Traceback (most recent call last):
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 412, in process_ws_message
    await self.on_message(jdata, jdata.get("action"))
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 344, in on_message
    await self.on_action(enum_action, message)
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 398, in on_action
    await self.on_stdin(message.get("input"))
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 375, in on_stdin
    action, data = self.stdin_to_action(stdin)
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 370, in stdin_to_action
    return Action.PreviewIndices, [int(i.strip()) for i in data]
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 370, in <listcomp>
    return Action.PreviewIndices, [int(i.strip()) for i in data]
ValueError: invalid literal for int() with base 10: '35,'
```

If I try to run it a second time, that traceback repeats, and this one is added:

```
Traceback (most recent call last):
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 412, in process_ws_message
    await self.on_message(jdata, jdata.get("action"))
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 344, in on_message
    await self.on_action(enum_action, message)
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 398, in on_action
    await self.on_stdin(message.get("input"))
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 375, in on_stdin
    action, data = self.stdin_to_action(stdin)
  File "/Users/stephennixon/code/coldtype/venv/lib/pyt%    
```

**Comment by stenson** [comment]
Ah yeah, again didn't see this until now, but that's fixed now — the commas were unnecessary and incorrect in the docs, so it should've been (and now is), just `pf 35 36 37` to get multiple frames.
