### ISSUE TITLE
'animations/media/organ.mid' missing

### ISSUE THREAD

**Issue by arrowtype** [goodhertz/coldtype-examples#2]
It seems that 'animations/media/organ.mid' is missing from the media:

```
▶ coldtype animations/vulfbach.py
>>> CAUGHT COLDTYPE RENDER
Traceback (most recent call last):
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/renderer/__init__.py", line 145, in reload
    self.program = run_path(str(self.filepath))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/stephennixon/code/coldtype-examples/animations/vulfbach.py", line 4, in <module>
    midi = MidiReader("animations/media/organ.mid", bpm=183, fps=30)
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/coldtype/animation/midi.py", line 132, in __init__
    mid = mido.MidiFile(str(midi_path))
  File "/Users/stephennixon/code/coldtype/venv/lib/python3.7/site-packages/mido/midifiles/midifiles.py", line 315, in __init__
    with io.open(filename, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'animations/media/organ.mid'
```

**Comment by stenson** [comment]
fixed in ca14c2a693dc13a794acae3c303d57aab25d3dff
